# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_geneSetPerm <- function(stats, rinds, Nsim) {
    .Call(`_ribiosGSEA_cpp_geneSetPerm`, stats, rinds, Nsim)
}

list2mat <- function(data) {
    .Call(`_ribiosGSEA_list2mat`, data)
}

